#-----------------------------------------------------------------
# Buggy grammar - !. . Can't ever match
# But the parser doesn't catch it.
#-----------------------------------------------------------------

Grammar~  ::=  WS? Sum !. .
Sum~2     ::=  Prod ((ADD | SUB) Prod)*
Prod~2    ::=  Power ((MUL | DIV) Power)*
Power~2   ::=  Unary ('^' Power)*
Unary~2   ::=  '-'? Term
Term~     ::=  NUMBER | '(' Sum ')'

MUL         =  '*'
DIV         =  '/'
ADD         =  '+'
SUB         =  '-'
NUMBER      =  DIGIT+ ('.' DIGIT+ | [eE] [-+]? DIGIT+ )?
DIGIT~      =  [0-9]
